sonar.projectName=dapr
sonar.projectVersion=1.0
sonar.sources=.
sonar.exclusions=**/vendor/**,coverage*.out,coverage.html
sonar.go.coverage.reportPaths=coverage-combined.out
sonar.coverage.exclusions=**/*.pb.go,**/zz_generated*.go,**/testdata/**,\
  **/cmd/**,\
  **/tests/**,\
  **/pkg/testing/**,\
  **/pkg/channel/testing/**,\
  **/pkg/client/clientset/**,\
  **/pkg/client/informers/**,\
  **/pkg/client/listers/**,\
  **/pkg/runtime/runtime.go,\
  **/pkg/runtime/cli.go,\
  **/pkg/operator/operator.go,\
  **/pkg/operator/client/**,\
  **/pkg/sentry/sentry.go
sonar.go.maxLineLength=240
sonar.c.file.suffixes=-
sonar.cpp.file.suffixes=-
sonar.objc.file.suffixes=-
sonar.scm.provider=git
